title: advoid - avoid ads!
email: info@advoid.net
description: "The device for blocking ads and speeding up all devices in your network." 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://advoid.net" # the base hostname & protocol for your site
twitter_username: advoid_
github_username:  advoid
paginate:      5
paginate_path: "news/page:num/"
permalink:     /news/:year/:month/:day/:title/
markdown: kramdown
